algoritmo "semnome"
// Função :
// Autor :
// Data : 27/04/2013
// Seção de Declarações 
var
   numero: inteiro
inicio
// Seção de Comandos
   escreval("Digite um número.")
   leia(numero)
   
   se (numero = 0) entao
      escreval("Zero")
   senao
        se (numero > 0) entao
           escreval("Número Positivo")
        Senao
           escreval("Número Negativo")
        fimse
   fimse
fimalgoritmo
