algoritmo "semnome"
// Função :
// Autor :
// Data : 27/04/2013
// Seção de Declarações 
var
   numero1, numero2: inteiro
inicio
// Seção de Comandos
   escreval("Digite um número.")
   leia(numero1)
   escreval("Digite mais um número. Juro que é a ultima vez que peço")
   leia(numero2)
   
   se (numero1 > numero2) entao
      escreva("Número:", numero1, " é maior")
   senao
      escreval("Número:", numero2, " é maior")
   fimse

fimalgoritmo
